#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='core audio'
PROVIDES='x11'
DESCRIPTION='VNC-based X11 backend. Enables tabbed sessions but is the slowest.'
CHROOTBIN='croutonpowerd croutonxinitrc-wrapper xinit'
CHROOTETC='xserverrc-vnc xserverrc-local.example'
EXTENSION='iabmpiboiopbgfabjmgeedhcmjenhbla'

# Check if the extension is installed and add a mark to the preparation script
if [ "$TARGETS" != 'help' -a "$TARGETS" != 'check' ]; then
    if [ -d "/home/chronos/user/Extensions/$EXTENSION" ]; then
        echo 'VNC_EXTENSION_INSTALLED=y'
    else
        echo 'VNC_EXTENSION_INSTALLED=n'
    fi
fi

. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
XMETHOD="${XMETHOD:-vnc}"

install --minimal tightvncserver dmz-cursor-theme xterm xfonts-base xinit

if [ "$VNC_EXTENSION_INSTALLED" != 'y' ]; then
    TIPS="$TIPS
You should install a VNC extension to view the graphical session. Recommended:
https://chrome.google.com/webstore/detail/iabmpiboiopbgfabjmgeedhcmjenhbla
"
fi

### append x11-common
